"""Knightmare: a self-play reinforcement-learning chess engine.

The package follows the AlphaZero recipe: a deep residual policy/value
network trained from games generated by Monte-Carlo Tree Search self-play,
optionally bootstrapped from human PGN data.

Sub-modules:
    board       Board-to-tensor encoding (17 input planes).
    encoding    AlphaZero-style 73-plane action encoding (4672 actions).
    network     PolicyValueNet with squeeze-and-excitation residual tower.
    mcts        PUCT search with Dirichlet noise and batched evaluation.
    selfplay    Self-play game generator that writes HDF5 replay buffers.
    train       Supervised / RL training loop with AMP + EMA + cosine LR.
    eval        Arena that pits two checkpoints against each other.
    ingest      Lichess PGN -> HDF5 ingestion pipeline.
    uci         Minimal UCI protocol implementation.
    replay      HDF5 replay buffer reader/writer.
    cli         Typer-based command-line entry point.
"""

from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("knightmare")
except PackageNotFoundError:  # pragma: no cover - editable install fallback
    __version__ = "0.0.0+unknown"

from .board import board_to_tensor
from .encoding import index_to_move, move_to_index
from .network import PolicyValueNet, ResidualBlock

__all__ = [
    "PolicyValueNet",
    "ResidualBlock",
    "__version__",
    "board_to_tensor",
    "index_to_move",
    "move_to_index",
]
